version: '2.1'

services:
    zoo1:
        image: zookeeper:3.5
        #restart: always
        hostname: zoo1
        container_name: zoo1
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
        volumes:
           - /mnt/zookeeper/zoo1/data:/data
           - /mnt/zookeeper/zoo1/datalog:/datalog
        networks:
          - kafka-net

    zoo2:
        image: zookeeper:3.5
        #restart: always
        hostname: zoo2
        container_name: zoo2
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
        volumes:
           - /mnt/zookeeper/zoo2/data:/data
           - /mnt/zookeeper/zoo2/datalog:/datalog
        networks:
          - kafka-net
    zoo3:
        image: zookeeper:3.5
        #restart: always
        hostname: zoo3
        container_name: zoo3
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
        volumes:
           - /mnt/zookeeper/zoo3/data:/data
           - /mnt/zookeeper/zoo3/datalog:/datalog
        networks:
          - kafka-net

    kafka1:
        image: wurstmeister/kafka
        #restart: always
        hostname: kafka1
        container_name: kafka1
        ports:
           - 9092:9092
        environment:
           KAFKA_ADVERTISED_HOST_NAME: kafka1
           KAFKA_ADVERTISED_PORT: 9092
           KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
           KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
           KAFKA_LISTENERS: PLAINTEXT://kafka1:9092
           KAFKA_BROKER_ID: 1
        volumes:
           - /mnt/kafka/kafka1/logs:/kafka
        external_links:
           - zoo1
           - zoo2
           - zoo3
        networks:
          - kafka-net

    kafka2:
        image: wurstmeister/kafka
        #restart: always
        hostname: kafka2
        container_name: kafka2
        ports:
           - 9093:9093
        environment:
           KAFKA_ADVERTISED_HOST_NAME: kafka2
           KAFKA_ADVERTISED_PORT: 9093
           KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
           KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
           KAFKA_LISTENERS: PLAINTEXT://kafka2:9093
           KAFKA_BROKER_ID: 2
        volumes:
           - /mnt/kafka/kafka2/logs:/kafka
        external_links:
           - zoo1
           - zoo2
           - zoo3
        networks:
           - kafka-net
    kafka3:
        image: wurstmeister/kafka
        #restart: always
        hostname: kafka3
        container_name: kafka3
        ports:
           - 9094:9094
        environment:
           KAFKA_ADVERTISED_HOST_NAME: kafka3
           KAFKA_ADVERTISED_PORT: 9094
           KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
           KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
           KAFKA_LISTENERS: PLAINTEXT://kafka3:9094
           KAFKA_BROKER_ID: 3
        volumes:
           - /mnt/kafka/kafka3/logs:/kafka
        external_links:
           - zoo1
           - zoo2
           - zoo3
        networks:
          - kafka-net

    kafka-manager:
        image: kafkamanager/kafka-manager
        #restart: always
        hostname: kafka-manager
        container_name: kafka-manager
        environment:
          ZK_HOSTS: zoo1:2181,zoo2:2181,zoo3:2181
          APPLICATION_SECRET: "letmein"
        ports:
          - "39000:9000"
        networks:
          - kafka-net
networks:
  kafka-net:
    external:
      name: docker-network-kafka
